### ISSUE TITLE
[FR] Setting for auto-expand unlinked mentions

### ISSUE THREAD

**Issue by N3C2L** [Benature/obsidian-default-query-in-backlink#1]
Thank you for this useful plugin.

In the backlinks sidebar the unlinked mentions are always expanded when I click on a new note, which is great and I love.

However, inside a note, the unlinked mentions are always collapsed and that's annoying.
It's sad that that the Obsidian core backlink feature don't allow us to auto-expand this section.

May I ask if you could add a setting to your plugin which auto-expand the unlinked mentions when a note is opened?

 That would really help my workflow, as I need the unlinked mentions very often to have a feedback what I didn't link recently.

**Comment by N3C2L** [comment]
I'm not a dev, but really would like to hear your opinion on that FR.
I would be using this auto-expanding feature specifically for my tag pages.
I think a lot of people would love such a setting in your addon.
No one else implemented such a feature in any backlink plugin.

**Comment by Benature** [comment]
I will add this feature if I can implement it. (I know how to make it but I'm not 100% sure until I actually make it.) It will be developed in about April, I'm too busy in march. 🥲

**Comment by N3C2L** [comment]
Thank you very much for that. Yes, it's not a problem if this happens a little later.

**Comment by Benature** [comment]
Hi, this feature is supported in version `0.1.0-b2`. It is a beta version. If you are interested, you can install the beta version by [BRAT](https://github.com/TfTHacker/obsidian42-brat) to have an early try :)

**Comment by Benature** [comment]
0.1.0 has been released.

**Comment by N3C2L** [comment]
Thank you very much!
I tested it in my vaults and the new settings are awesome!
edit: all working fine, sorry for the confusion.
